[build]
  publish = "."

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache"

[[edge_functions]]
  path = "/*.html"
  function = "inject-env"

[[redirects]]
  from = "/"
  to = "/login.html"
  status = 200
